#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Induce provisional UD mapping tables for the Kadiwéu UD conversion pipeline.

This utility derives statistical mapping tables between Tycho Brahe source
annotations and manually corrected Universal Dependencies annotations.

Inputs
------
- Kadiwéu token table generated by kadiweu_json_to_token_table.py
- Gold CoNLL-U treebank: data/treebank/kbc_unicamp-ud-test.conllu

The token table must contain sent_uid, token_ordinal, token_tag_source,
split_tags, and chunk_memberships columns.

Outputs
-------
- source_tag_to_upos.tsv
- source_tag_splitseq_to_upos.tsv
- source_tag_to_feats.tsv
- source_tag_chunk_to_deprel.tsv
- alignment_diagnostics.tsv

Repository layout
-----------------
kadiweu/
├── data/
│   ├── ped-gramm.json
│   ├── hil-data.json
│   ├── van-data.json
│   ├── token_tables/
│   │   ├── ped-gramm-tokens.tsv
│   │   ├── hil-data-tokens.tsv
│   │   ├── van-data-tokens.tsv
│   │   └── all-tokens.tsv
│   ├── treebank/
│   │   └── kbc_unicamp-ud-test.conllu
│   └── ud_mappings/
└── src/
    ├── kadiweu_json_to_token_table.py
    └── induce_kadiweu_ud_mappings.py

Alignment policy
----------------
Sentence alignment is UID-based:

    token table sent_uid  <->  CoNLL-U # sent_uid

Token alignment is ordinal within each UID-matched sentence.

Before token alignment:

- source-side empty-category tokens (e.g. `*T*`) are ignored;
- one final gold punctuation token is ignored when it was added during
  conversion and is absent from `# text_orig`.

After these normalizations, the source and gold token counts must agree
exactly; otherwise, the sentence is rejected for mapping induction.

Multiword-token (MWT) lines and empty nodes are ignored when reading
CoNLL-U, so only ordinary syntactic tokens participate in mapping induction.

Usage
-----
    python3 induce_kadiweu_ud_mappings.py \
      ../data/token_tables/all-tokens.tsv \
      ../data/treebank/kbc_unicamp-ud-test.conllu \
      --outdir ../data/ud_mappings
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Tuple
import string

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DEFAULT_OUTDIR = PROJECT_ROOT / "data" / "ud_mappings"

FINAL_PUNCT_FOR_ALIGNMENT = set(string.punctuation) | {"…"}

def filter_source_learning_tokens(
    rows: List[Dict[str, str]]
    ) -> List[Dict[str, str]]:
    """
    Remove source tokens that do not correspond to overt surface tokens.
    """
    return [
        row
        for row in rows
        if row.get("token_form") != "*T*"
    ]


def text_orig_has_final_punct(sent: Dict) -> bool:
    """Return True if # text_orig already ends in sentence-final punctuation."""
    text_orig = sent.get("meta", {}).get("text_orig", "").strip()
    return bool(text_orig) and text_orig.endswith(tuple(FINAL_PUNCT_FOR_ALIGNMENT))


def gold_tokens_for_alignment(sent: Dict) -> Tuple[List[Dict[str, str]], bool]:
    """
    Return gold tokens for source-token alignment.

    If the gold sentence has one final punctuation token that was not present
    in # text_orig, remove it. This avoids false token-count mismatches caused
    by converter-added final punctuation while preserving source punctuation.
    """
    tokens = list(sent["tokens"])

    if (
        tokens
        and tokens[-1].get("upos") == "PUNCT"
        and not text_orig_has_final_punct(sent)
    ):
        return tokens[:-1], True

    return tokens, False


def parse_feats(feats: str) -> str:
    if not feats or feats == "_":
        return "_"
    parts = [p for p in feats.split("|") if p]
    return "|".join(sorted(parts))


def read_tsv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def read_conllu(path: Path) -> List[Dict]:
    sentences = []
    sent = {"meta": {}, "tokens": []}

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                if sent["tokens"]:
                    sentences.append(sent)
                sent = {"meta": {}, "tokens": []}
                continue

            if line.startswith("#"):
                if "=" in line:
                    key, value = line[1:].split("=", 1)
                    sent["meta"][key.strip()] = value.strip()
                continue

            cols = line.split("\t")
            if len(cols) != 10:
                continue
            if "-" in cols[0] or "." in cols[0]:
                continue

            sent["tokens"].append(
                {
                    "id": cols[0],
                    "form": cols[1],
                    "lemma": cols[2],
                    "upos": cols[3],
                    "xpos": cols[4],
                    "feats": parse_feats(cols[5]),
                    "head": cols[6],
                    "deprel": cols[7],
                    "deps": cols[8],
                    "misc": cols[9],
                }
            )

    if sent["tokens"]:
        sentences.append(sent)

    return sentences


def conllu_sent_uid(sent: Dict) -> str:
    """Return the CoNLL-U # sent_uid metadata value, or an empty string."""
    return sent.get("meta", {}).get("sent_uid", "")


def group_tsv_by_sent_uid(rows: List[Dict[str, str]]) -> Dict[str, List[Dict[str, str]]]:
    """
    Group token-table rows by sent_uid.

    The token table is generated from Kadiwéu Tycho Brahe JSON source files.
    Its sent_uid column corresponds to the JSON sentence uid and is aligned
    with the CoNLL-U # sent_uid metadata field.
    """
    grouped = defaultdict(list)

    for row in rows:
        sent_uid = row.get("sent_uid", "")
        if not sent_uid:
            continue
        grouped[sent_uid].append(row)

    for sent_uid in grouped:
        grouped[sent_uid] = sorted(
            grouped[sent_uid],
            key=lambda r: int(r.get("token_ordinal", "0") or 0),
        )

    return grouped


def most_common_mapping(counter: Counter) -> Tuple[str, int, int]:
    if not counter:
        return ("", 0, 0)
    item, count = counter.most_common(1)[0]
    total = sum(counter.values())
    return (item, count, total)


def write_counter_table(path: Path, rows: List[List[str]], header: List[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t")
        w.writerow(header)
        w.writerows(rows)

def token_sequence(tokens: List[Dict[str, str]]) -> str:
    """Return a compact FORM sequence for diagnostics."""
    return " ".join(tok.get("form", "") for tok in tokens)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Induce provisional UD mapping tables from a Kadiwéu token table "
            "and a gold CoNLL-U treebank using UID-based sentence alignment."
        ),
        epilog="""Example:
  python3 induce_kadiweu_ud_mappings.py \\
    ../data/token_tables/all-tokens.tsv \\
    ../data/treebank/kbc_unicamp-ud-test.conllu \\
    --outdir ../data/ud_mappings
""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "tokens_tsv",
        help="Token table generated by kadiweu_json_to_token_table.py.",
    )
    ap.add_argument(
        "gold_conllu",
        help="Gold CoNLL-U file, usually data/treebank/kbc_unicamp-ud-test.conllu.",
    )
    ap.add_argument(
        "--outdir",
        default=DEFAULT_OUTDIR,
        type=Path,
        help="Output directory for induced mapping tables.",
    )
    args = ap.parse_args()

    tsv_rows = read_tsv(Path(args.tokens_tsv))
    conllu_sents = read_conllu(Path(args.gold_conllu))
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    tsv_by_uid = group_tsv_by_sent_uid(tsv_rows)

    upos_by_tag = Counter()
    upos_by_tagseq = Counter()
    feats_by_tag = Counter()
    deprel_by_tagchunk = Counter()
    diagnostics = []
    mismatch_details = []

    matched = 0
    missing_gold_uid = 0
    no_uid_match = 0
    token_count_mismatches = 0
    ignored_final_punct = 0

    for sent in conllu_sents:
        sent_uid = conllu_sent_uid(sent)

        if not sent_uid:
            missing_gold_uid += 1
            diagnostics.append(
                [
                    "",
                    "GOLD_SENTENCE_MISSING_SENT_UID",
                    "",
                    "",
                    "",   # src_forms
                    "",   # gold_forms
                    "",   # ignored_final_punct
                    "",   # text_orig
                ]
            )
            continue

        src_rows = filter_source_learning_tokens(
            tsv_by_uid.get(sent_uid, [])
        )

        if not src_rows:
            no_uid_match += 1
            diagnostics.append(
                [
                    sent_uid,
                    "NO_UID_MATCH",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                ]
            )
            continue

        gold_toks, ignored_punct = gold_tokens_for_alignment(sent)

        if ignored_punct:
            ignored_final_punct += 1
        
        if len(src_rows) != len(gold_toks):
            token_count_mismatches += 1
            diagnostics.append(
                [
                    sent_uid,
                    "TOKEN_COUNT_MISMATCH",
                    str(len(src_rows)),
                    str(len(gold_toks)),
                    " ".join(row.get("token_form", "") for row in src_rows),
                    token_sequence(gold_toks),
                    "yes" if ignored_punct else "no",
                    sent.get("meta", {}).get("text_orig", ""),
                ]
            )
            mismatch_details.append(
                {
                    "sent_uid": sent_uid,
                    "src_rows": src_rows,
                    "gold_toks": gold_toks,
                    "text_orig": sent.get("meta", {}).get("text_orig", ""),
                }
            )
            continue

        for i in range(len(gold_toks)):
            src = src_rows[i]
            gold = gold_toks[i]

            source_tag = src.get("token_tag_source", "")
            splitseq = src.get("split_tags", "")
            chunk = src.get("chunk_memberships", "")
            upos = gold.get("upos", "")
            feats = gold.get("feats", "_")
            deprel = gold.get("deprel", "")

            upos_by_tag[(source_tag, upos)] += 1
            upos_by_tagseq[(source_tag, splitseq, upos)] += 1
            feats_by_tag[(source_tag, feats)] += 1

            if chunk:
                for ch in chunk.split("|"):
                    if ch:
                        deprel_by_tagchunk[(source_tag, ch, deprel)] += 1

        matched += 1

    gold_uids = {
        conllu_sent_uid(sent)
        for sent in conllu_sents
        if conllu_sent_uid(sent)
    }

    token_table_uids_not_in_gold = sorted(set(tsv_by_uid) - gold_uids)

    for sent_uid in token_table_uids_not_in_gold:
        diagnostics.append(
        [
            sent_uid,
            "TOKEN_TABLE_UID_NOT_IN_GOLD",
            str(len(tsv_by_uid[sent_uid])),
            "",
            "",
            "",
            "",
            "",
        ]
        )
    # collapse to readable summaries
    by_tag = defaultdict(Counter)
    for (tag, upos), count in upos_by_tag.items():
        by_tag[tag][upos] += count

    by_tagseq = defaultdict(Counter)
    for (tag, seq, upos), count in upos_by_tagseq.items():
        by_tagseq[(tag, seq)][upos] += count

    by_feats = defaultdict(Counter)
    for (tag, feats), count in feats_by_tag.items():
        by_feats[tag][feats] += count

    by_tagchunk = defaultdict(Counter)
    for (tag, ch, dep), count in deprel_by_tagchunk.items():
        by_tagchunk[(tag, ch)][dep] += count

    source_tag_rows = []
    for tag in sorted(by_tag):
        best, count, total = most_common_mapping(by_tag[tag])
        source_tag_rows.append([tag, best, str(count), str(total), f"{count/total:.3f}"])

    splitseq_rows = []
    for key in sorted(by_tagseq):
        tag, seq = key
        best, count, total = most_common_mapping(by_tagseq[key])
        splitseq_rows.append([tag, seq, best, str(count), str(total), f"{count/total:.3f}"])

    feats_rows = []
    for tag in sorted(by_feats):
        best, count, total = most_common_mapping(by_feats[tag])
        feats_rows.append([tag, best, str(count), str(total), f"{count/total:.3f}"])

    dep_rows = []
    for key in sorted(by_tagchunk):
        tag, ch = key
        best, count, total = most_common_mapping(by_tagchunk[key])
        dep_rows.append([tag, ch, best, str(count), str(total), f"{count/total:.3f}"])

    write_counter_table(
        outdir / "source_tag_to_upos.tsv",
        source_tag_rows,
        ["source_tag", "best_upos", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "source_tag_splitseq_to_upos.tsv",
        splitseq_rows,
        ["source_tag", "split_tag_sequence", "best_upos", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "source_tag_to_feats.tsv",
        feats_rows,
        ["source_tag", "best_feats", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "source_tag_chunk_to_deprel.tsv",
        dep_rows,
        ["source_tag", "chunk_label", "best_deprel", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "alignment_diagnostics.tsv",
        diagnostics,
        [
            "sent_uid",
            "status",
            "src_count",
            "gold_count",
            "src_forms",
            "gold_forms",
            "ignored_final_punct",
            "text_orig",
        ],
        )

    print("Alignment summary:")
    print(f"  Gold sentences:                 {len(conllu_sents)}")
    print(f"  Token-table sentences:          {len(tsv_by_uid)}")
    print(f"  Usable aligned sentences:       {matched}")
    print(f"  Gold sentences missing UID:     {missing_gold_uid}")
    print(f"  Gold sentences without UID match:{no_uid_match}")
    print(f"  Token-count mismatches:         {token_count_mismatches}")
    print(f"  Ignored final punctuation:      {ignored_final_punct}")
    print(f"  Token-table UIDs not in gold:   {len(token_table_uids_not_in_gold)}")
    print(f"Wrote induced tables to:          {outdir}")
    if mismatch_details:
        print()
        print("Token-count mismatches")
        print("=" * 22)

        for m in mismatch_details:
            print()
            print(f"sent_uid: {m['sent_uid']}")
            print()

            print(f"Source ({len(m['src_rows'])}):")
            for i, row in enumerate(m["src_rows"], 1):
                print(f"  {i:>2}  {row.get('token_form', '')}")

            print()

            print(f"Gold ({len(m['gold_toks'])}):")
            for i, tok in enumerate(m["gold_toks"], 1):
                print(f"  {i:>2}  {tok.get('form', '')}")

            print()

            print("text_orig:")
            print(f"  {m['text_orig']}")

            print()
            print("-" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())