#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Induce provisional UD mapping tables for Kadiwéu from:

- gramatica-pedagogica.json
- kadiweu_tokens.tsv
- kbc_unicamp-ud-test.conllu

Outputs:
- source_tag_to_upos.tsv
- source_tag_splitseq_to_upos.tsv
- source_tag_to_feats.tsv
- source_tag_chunk_to_deprel.tsv
- alignment_diagnostics.tsv

Assumptions
-----------
1. The TSV was generated by kadiweu_json_to_token_table.py.
2. The CoNLL-U file contains gold or semi-gold UD analyses.
3. Sentence alignment is attempted by normalized sentence text first.
4. Token alignment is attempted by ordinal position within the sentence.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Tuple, Optional


def norm(text: str) -> str:
    text = text or ""
    text = text.strip().lower()
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = unicodedata.normalize("NFC", text)
    text = re.sub(r"\s+", " ", text)
    return text


def parse_feats(feats: str) -> str:
    if not feats or feats == "_":
        return "_"
    parts = [p for p in feats.split("|") if p]
    return "|".join(sorted(parts))


def read_tsv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def read_conllu(path: Path) -> List[Dict]:
    sentences = []
    sent = {"meta": {}, "tokens": []}

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                if sent["tokens"]:
                    sentences.append(sent)
                sent = {"meta": {}, "tokens": []}
                continue

            if line.startswith("#"):
                if "=" in line:
                    key, value = line[1:].split("=", 1)
                    sent["meta"][key.strip()] = value.strip()
                continue

            cols = line.split("\t")
            if len(cols) != 10:
                continue
            if "-" in cols[0] or "." in cols[0]:
                continue

            sent["tokens"].append(
                {
                    "id": cols[0],
                    "form": cols[1],
                    "lemma": cols[2],
                    "upos": cols[3],
                    "xpos": cols[4],
                    "feats": parse_feats(cols[5]),
                    "head": cols[6],
                    "deprel": cols[7],
                    "deps": cols[8],
                    "misc": cols[9],
                }
            )

    if sent["tokens"]:
        sentences.append(sent)

    return sentences


def group_tsv_by_sentence(rows: List[Dict[str, str]]) -> Dict[str, List[Dict[str, str]]]:
    grouped = defaultdict(list)
    for row in rows:
        key = norm(row.get("sent_text", ""))
        grouped[key].append(row)
    for key in grouped:
        grouped[key] = sorted(grouped[key], key=lambda r: int(r.get("token_ordinal", "0") or 0))
    return grouped


def conllu_sentence_key(sent: Dict) -> str:
    for key in ("text", "sent_id"):
        if key in sent["meta"]:
            value = sent["meta"][key]
            if key == "sent_id":
                # sometimes sent_id is not human-readable text, so prefer text if present
                pass
    if "text" in sent["meta"]:
        return norm(sent["meta"]["text"])
    token_text = " ".join(tok["form"] for tok in sent["tokens"])
    return norm(token_text)


def most_common_mapping(counter: Counter) -> Tuple[str, int, int]:
    if not counter:
        return ("", 0, 0)
    item, count = counter.most_common(1)[0]
    total = sum(counter.values())
    return (item, count, total)


def write_counter_table(path: Path, rows: List[List[str]], header: List[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t")
        w.writerow(header)
        w.writerows(rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("tokens_tsv")
    ap.add_argument("gold_conllu")
    ap.add_argument("--outdir", default="induced_mappings")
    args = ap.parse_args()

    tsv_rows = read_tsv(Path(args.tokens_tsv))
    conllu_sents = read_conllu(Path(args.gold_conllu))
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    tsv_by_sent = group_tsv_by_sentence(tsv_rows)

    upos_by_tag = Counter()
    upos_by_tagseq = Counter()
    feats_by_tag = Counter()
    deprel_by_tagchunk = Counter()
    diagnostics = []

    matched = 0

    for sent in conllu_sents:
        key = conllu_sentence_key(sent)
        src_rows = tsv_by_sent.get(key)

        if not src_rows:
            diagnostics.append([key, "NO_SENTENCE_MATCH", "", ""])
            continue

        gold_toks = sent["tokens"]
        n = min(len(src_rows), len(gold_toks))

        if len(src_rows) != len(gold_toks):
            diagnostics.append([key, "TOKEN_COUNT_MISMATCH", str(len(src_rows)), str(len(gold_toks))])

        for i in range(n):
            src = src_rows[i]
            gold = gold_toks[i]

            source_tag = src.get("token_tag_source", "")
            splitseq = src.get("split_tags", "")
            chunk = src.get("chunk_memberships", "")
            upos = gold.get("upos", "")
            feats = gold.get("feats", "_")
            deprel = gold.get("deprel", "")

            upos_by_tag[(source_tag, upos)] += 1
            upos_by_tagseq[(source_tag, splitseq, upos)] += 1
            feats_by_tag[(source_tag, feats)] += 1

            if chunk:
                for ch in chunk.split("|"):
                    if ch:
                        deprel_by_tagchunk[(source_tag, ch, deprel)] += 1

        matched += 1

    # collapse to readable summaries
    by_tag = defaultdict(Counter)
    for (tag, upos), count in upos_by_tag.items():
        by_tag[tag][upos] += count

    by_tagseq = defaultdict(Counter)
    for (tag, seq, upos), count in upos_by_tagseq.items():
        by_tagseq[(tag, seq)][upos] += count

    by_feats = defaultdict(Counter)
    for (tag, feats), count in feats_by_tag.items():
        by_feats[tag][feats] += count

    by_tagchunk = defaultdict(Counter)
    for (tag, ch, dep), count in deprel_by_tagchunk.items():
        by_tagchunk[(tag, ch)][dep] += count

    source_tag_rows = []
    for tag in sorted(by_tag):
        best, count, total = most_common_mapping(by_tag[tag])
        source_tag_rows.append([tag, best, str(count), str(total), f"{count/total:.3f}"])

    splitseq_rows = []
    for key in sorted(by_tagseq):
        tag, seq = key
        best, count, total = most_common_mapping(by_tagseq[key])
        splitseq_rows.append([tag, seq, best, str(count), str(total), f"{count/total:.3f}"])

    feats_rows = []
    for tag in sorted(by_feats):
        best, count, total = most_common_mapping(by_feats[tag])
        feats_rows.append([tag, best, str(count), str(total), f"{count/total:.3f}"])

    dep_rows = []
    for key in sorted(by_tagchunk):
        tag, ch = key
        best, count, total = most_common_mapping(by_tagchunk[key])
        dep_rows.append([tag, ch, best, str(count), str(total), f"{count/total:.3f}"])

    write_counter_table(
        outdir / "source_tag_to_upos.tsv",
        source_tag_rows,
        ["source_tag", "best_upos", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "source_tag_splitseq_to_upos.tsv",
        splitseq_rows,
        ["source_tag", "split_tag_sequence", "best_upos", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "source_tag_to_feats.tsv",
        feats_rows,
        ["source_tag", "best_feats", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "source_tag_chunk_to_deprel.tsv",
        dep_rows,
        ["source_tag", "chunk_label", "best_deprel", "best_count", "total", "confidence"],
    )
    write_counter_table(
        outdir / "alignment_diagnostics.tsv",
        diagnostics,
        ["sentence_key", "status", "src_count", "gold_count"],
    )

    print(f"Matched {matched} gold sentence(s).")
    print(f"Wrote induced tables to {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())